version: "3"
services:
  app:
    container_name: logiudice
    build: .
    command: nodemon --watch . -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www
    links:
      - "mongo_budget:mongohost"
  mongo_budget:
    container_name: mongo_budget
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"